#!/bin/bash

sudo echo -n

if [ -z "$SRDebug" ] 
then
  echo "\$SRDEBUG not set, using Debug as default"
  xcodebuild -target jailbreakgeniusassistant -configuration Debug > .logs/xcode.log
  mv ./Build/Debug-iphoneos/jailbreakgeniusassistant.app ./
else
  if [ $SRDebug == 1 ]
  then
    xcodebuild -target jailbreakgeniusassistant -configuration Debug > .logs/xcode.log
    mv ./Build/Debug-iphoneos/jailbreakgeniusassistant.app ./
  else
    xcodebuild -target jailbreakgeniusassistant -configuration Release > .logs/xcode.log
    mv ./Build/Release-iphoneos/jailbreakgeniusassistant.app ./
  fi
fi

ldid -SEntitlements.plist ./jailbreakgeniusassistant.app/jailbreakgeniusassistant
rm -f ./jailbreakgeniusassistant.app/embedded.mobileprovision
mkdir ./com.samgisaninja.jailbreakgeniusassistant
cp -r ./Template/* ./com.samgisaninja.jailbreakgeniusassistant/
mkdir com.samgisaninja.jailbreakgeniusassistant/Applications/
mv jailbreakgeniusassistant.app com.samgisaninja.jailbreakgeniusassistant/Applications/
sudo fakeroot chmod 6755 com.samgisaninja.jailbreakgeniusassistant/Applications/jailbreakgeniusassistant.app/jailbreakgeniusassistant
rm -rf ./Build
rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
sudo fakeroot dpkg-deb -Zgzip -b com.samgisaninja.jailbreakgeniusassistant com.samgisaninja.jailbreakgeniusassistant.deb && rm -r com.samgisaninja.jailbreakgeniusassistant

if [ -z "$IDEVICEIP" ] 
then
	echo "\$IDEVICEIP not found, please type in your iDevice's ip address (local for localhost:2222)"
	read IDEVICEIP
fi
if [ "$IDEVICEIP" == "local" ]
then
	echo "Trying to move deb to device"
	scp -p 2222 com.samgisaninja.jailbreakgeniusassistant.deb root@localhost:/tmp
	echo "Trying to install deb"
	ssh -p 2222 root@localhost "dpkg -i /tmp/com.samgisaninja.jailbreakgeniusassistant.deb && uicache"
	echo "Success!"
else
	echo "Trying to move deb to device"
	scp com.samgisaninja.jailbreakgeniusassistant.deb root@$IDEVICEIP:/tmp
	echo "Trying to install deb"
	ssh root@$IDEVICEIP "dpkg -i /tmp/com.samgisaninja.jailbreakgeniusassistant.deb && uicache"
	echo "Success!"
fi

## Changes made by nobbele/4ppleCracker
